"""add user email, consents, invitation target

Revision ID: 1434cd46851c
Revises: a18d0efd2a10
Create Date: 2026-09-02 11:25:30.795398
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1434cd46851c'
down_revision: str | None = 'a18d0efd2a10'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('health_data', 'email_report', 'ai_processing', name='consentkind', native_enum=False, length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.add_column('invitations', sa.Column('target_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'invitations', 'users', ['target_user_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_column('invitations', 'target_user_id')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    # ### end Alembic commands ###
