"""initial schema

Revision ID: a18d0efd2a10
Revises: 
Create Date: 2026-09-02 10:14:51.700971
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a18d0efd2a10'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('senior', 'guardian', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('activity_signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('screen_on_count', sa.Integer(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('light_level', sa.Integer(), nullable=True),
    sa.Column('battery', sa.SmallInteger(), nullable=True),
    sa.Column('is_charging', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_signals_recorded_at'), 'activity_signals', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_activity_signals_user_id'), 'activity_signals', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_at'), 'audit_logs', ['at'], unique=False)
    op.create_table('daily_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('meal_done', sa.SmallInteger(), nullable=False),
    sa.Column('med_taken', sa.SmallInteger(), nullable=False),
    sa.Column('med_total', sa.SmallInteger(), nullable=False),
    sa.Column('mood', sa.Enum('good', 'normal', 'bad', name='moodvalue', native_enum=False, length=20), nullable=True),
    sa.Column('activity_level', sa.Enum('high', 'normal', 'low', name='activitylevel', native_enum=False, length=20), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_date', name='uq_daily_report')
    )
    op.create_index(op.f('ix_daily_reports_report_date'), 'daily_reports', ['report_date'], unique=False)
    op.create_index(op.f('ix_daily_reports_user_id'), 'daily_reports', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='deviceplatform', native_enum=False, length=20), nullable=False),
    sa.Column('push_token', sa.String(length=255), nullable=True),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('push_token', name='uq_device_push_token')
    )
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('families',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_checks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('breakfast', 'lunch', 'dinner', name='checkslot', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ate', 'skipped', name='mealstatus', native_enum=False, length=20), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_date', 'slot', name='uq_meal_check')
    )
    op.create_index(op.f('ix_meal_checks_check_date'), 'meal_checks', ['check_date'], unique=False)
    op.create_index(op.f('ix_meal_checks_user_id'), 'meal_checks', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('dose', sa.String(length=40), nullable=True),
    sa.Column('times', sa.JSON(), nullable=False),
    sa.Column('weekdays', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_user_id'), 'medications', ['user_id'], unique=False)
    op.create_table('mood_checks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('breakfast', 'lunch', 'dinner', name='checkslot', native_enum=False, length=20), nullable=False),
    sa.Column('mood', sa.Enum('good', 'normal', 'bad', name='moodvalue', native_enum=False, length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'check_date', 'slot', name='uq_mood_check')
    )
    op.create_index(op.f('ix_mood_checks_check_date'), 'mood_checks', ['check_date'], unique=False)
    op.create_index(op.f('ix_mood_checks_user_id'), 'mood_checks', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('font_scale', sa.Integer(), nullable=False),
    sa.Column('voice_guide', sa.Boolean(), nullable=False),
    sa.Column('notify_meal', sa.Boolean(), nullable=False),
    sa.Column('notify_medication', sa.Boolean(), nullable=False),
    sa.Column('notify_schedule', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings')
    )
    op.create_table('alerts',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('no_response', 'no_checks', 'missed_med', name='alerttype', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='alertseverity', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ack_by', sa.Uuid(), nullable=True),
    sa.Column('ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ack_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_family_id'), 'alerts', ['family_id'], unique=False)
    op.create_index(op.f('ix_alerts_occurred_at'), 'alerts', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_alerts_target_user_id'), 'alerts', ['target_user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('senior', 'guardian', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('relation', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('family_id', 'user_id', name='uq_family_member')
    )
    op.create_index(op.f('ix_family_members_family_id'), 'family_members', ['family_id'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('invitations',
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.Enum('senior', 'guardian', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_code'), 'invitations', ['code'], unique=True)
    op.create_table('medication_logs',
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'taken', 'missed', name='medicationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('reminder_level', sa.SmallInteger(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_id', 'scheduled_at', name='uq_medication_log')
    )
    op.create_index(op.f('ix_medication_logs_medication_id'), 'medication_logs', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_logs_scheduled_at'), 'medication_logs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_medication_logs_user_id'), 'medication_logs', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.Enum('hospital', 'other', name='schedulekind', native_enum=False, length=20), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('place', sa.String(length=100), nullable=True),
    sa.Column('notify_before_minutes', sa.Integer(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_family_id'), 'schedules', ['family_id'], unique=False)
    op.create_index(op.f('ix_schedules_start_at'), 'schedules', ['start_at'], unique=False)
    op.create_index(op.f('ix_schedules_target_user_id'), 'schedules', ['target_user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'expired', 'canceled', name='subscriptionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_family_id'), 'subscriptions', ['family_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_family_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_schedules_target_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_start_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_family_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_medication_logs_user_id'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_scheduled_at'), table_name='medication_logs')
    op.drop_index(op.f('ix_medication_logs_medication_id'), table_name='medication_logs')
    op.drop_table('medication_logs')
    op.drop_index(op.f('ix_invitations_code'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_family_id'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_alerts_target_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_occurred_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_family_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_mood_checks_user_id'), table_name='mood_checks')
    op.drop_index(op.f('ix_mood_checks_check_date'), table_name='mood_checks')
    op.drop_table('mood_checks')
    op.drop_index(op.f('ix_medications_user_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_meal_checks_user_id'), table_name='meal_checks')
    op.drop_index(op.f('ix_meal_checks_check_date'), table_name='meal_checks')
    op.drop_table('meal_checks')
    op.drop_table('families')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_daily_reports_user_id'), table_name='daily_reports')
    op.drop_index(op.f('ix_daily_reports_report_date'), table_name='daily_reports')
    op.drop_table('daily_reports')
    op.drop_index(op.f('ix_audit_logs_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_activity_signals_user_id'), table_name='activity_signals')
    op.drop_index(op.f('ix_activity_signals_recorded_at'), table_name='activity_signals')
    op.drop_table('activity_signals')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
