"""schedule reminders list and kinds

Revision ID: ad2cb81fc302
Revises: 83630e727ce9
Create Date: 2026-09-08 14:37:24.153450
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ad2cb81fc302'
down_revision: str | None = '83630e727ce9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('reminder_minutes', sa.JSON(), nullable=False))
    op.drop_column('schedules', 'notify_before_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('notify_before_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('schedules', 'reminder_minutes')
    # ### end Alembic commands ###
